### ISSUE TITLE
Facing an Issue

### ISSUE THREAD

**Issue by owlsecco** [StaticMania/portio-hugo#30]
Hi, i like this theme, thank you for it.
I recently added notes to it but i am facing an issue.
I made a new archetype, a list and single, a new directory under content, notesSection.yml, notesSection.html.
Upon deploying my website, it displays my notes on the blog area while leaving the notes area blank, how can i make sure notes appear on the notesSection and not on the blogSection.
The page note renders the notes fine, my issue is in the homepage.
Kindly help me

and if you can also help me fix the notes image issue, making images in notes optional and displaying the full note instead of just the title. Tried adding {{ .content }} but it didn't work

**Comment by owlsecco** [comment]
and if you can also help me fix the notes image issue, making images in notes optional and displaying the full note instead of just the title. Tried adding {{ .content }} but it didn't work

**Comment by Error6251** [comment]
Your problem is not clear. I think if you want to create a new page or a new section, your data will be on "data/notesSection.yml" On blogSection.html line 23 we used `{{ range first 3 (where $.Site.RegularPages "Type" "!=" "portfolio") }}` for telling show all file instead of portfolio  you can change it with show only "==" blog, notes or whatever you want to show...  And I can't say understand the problem with out the code for image not showing issue... It could be for `absURL` pipe or `{{ .Content }}` instead of `{{.content}}`

**Comment by stephenajulu** [comment]
> Your problem is not clear. I think if you want to create a new page or a new section, your data will be on "data/notesSection.yml" 
> 
> On blogSection.html line 23 we used `{{ range first 3 (where $.Site.RegularPages "Type" "!=" "portfolio") }}` for telling show all file instead of portfolio  you can change it with show only "==" blog, notes or whatever you want to show...
> 
> And I can't understand the problem without the code for image issue... It could be for `absURL` pipe or use `{{ .Content }}` instead of `{{ .content }}`

Thank you let me try this, if it fails, I'll send a screenshot of my code and the page.

**Comment by owlsecco** [comment]
I'll reopen this issue, if your advice fails, thank you very much. If it fails I'll send you the code and screenshot + how i would like it to render

**Comment by owlsecco** [comment]
Thank you, your solution worked!
Thank you very much. 
I now have a blog page for long form posts and a note page for short form posts.
