### ISSUE TITLE
White space after footer

### ISSUE THREAD

**Issue by AntoineSoetewey** [StaticMania/portio-hugo#46]
Hello,

There is a white space after the footer for the contact page (https://easystat.be/contact/):

<img width="1392" alt="Screenshot 2021-11-23 at 22 24 16" src="https://user-images.githubusercontent.com/17910063/143131668-a55b6f86-87af-47fa-8102-0af5abd6c424.png">

I don't have the same issue with other pages (for instance, https://easystat.be/rdv/):

<img width="1392" alt="Screenshot 2021-11-23 at 22 27 02" src="https://user-images.githubusercontent.com/17910063/143131906-00fdaeb9-0e2d-4944-9503-bb7db0dbf864.png">

Any idea how I could fix this by removing the white space?

The repo is available at https://github.com/AntoineSoetewey/easystat.

Thanks in advance for your help!

Regards,
Antoine

**Comment by Error6251** [comment]
I Think it is happening only in your site. Because you added this part https://github.com/StaticMania/portio-hugo/blob/ccae0510631bc00e477fa2438cdcd38022eaf5c9/layouts/contact/list.html#L41 
inside your `header` tag. This make code look weird.

There are lots of way to fix it.

If you want a quick fix, add ```style="display: none;"``` in https://github.com/StaticMania/portio-hugo/blob/ccae0510631bc00e477fa2438cdcd38022eaf5c9/layouts/contact/list.html#L7

Code will be...
```
<div class="animate-shape" style="display: none;">
```
_BTW This is not a good solution_
